export const protocols = [
  {
    id: "rsbtc",
    name: "Rosen Bridge",
    category: "Bridge",
    status: "Active",
    api: "/api/cardano-bitcoin",
    asset: "rsBTC",
    logo: "/logos/rosen.png",
    color: "orange",
    featured: true,
  },
  {
    id: "wanbtc",
    name: "Wanchain",
    category: "Bridge",
    status: "Active",
    api: "/api/cardano-bitcoin",
    asset: "wanBTC",
    logo: "/logos/wanchain.png",
    color: "blue",
    featured: true,
  },
  {
    id: "btckarma",
    name: "BTC Karma",
    category: "Staking",
    status: "Active",
    api: "/api/btc-karma",
    logo: "/logos/btckarma.png",
    color: "amber",
    featured: true,
  },
];
